source 'git@github.com:wemap/wemap-sdk-specrepo.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
platform :ios, '9.0'

target 'FusumaWemapExample' do
  project 'FusumaWemapExample.xcodeproj'
  pod 'FusumaWemap', :path => '../'
end
